spring:
  application:
    name: clothing store backend
  web:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: never
    resources:
      add-mappings: false
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
    show-summary: summary

app:
  allowed-origins: ${ALLOWED_ORIGINS:http://localhost:3000}
jwt:
  secret: ${JWT_SECRET}
  expires: ${JWT_EXPIRES:3600000}