spring:
  application:
    name: clothing store backend
  web:
    error:
      include-message: always
      include-binding-errors: always
      include-stacktrace: never

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    name: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
